baseURL: "https://watobii.github.io/"
canonifyurls: false
publishDir: "docs"
title: watobi
paginate: 5
theme: PaperMod

enableEmoji: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: watobi
  description: "Blog of watobi."
  keywords: [Blog, Portfolio, PaperMod]
  author: watobi
  # author: ["Me", "You"] # multiple authors
  images: ["watobi.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "Thinking_Face_Emoji_large.png"
    # favicon16x16: "Thinking_Face_Emoji_large.png"
    # favicon32x32: "Thinking_Face_Emoji_large.png"
    # apple_touch_icon: "Thinking_Face_Emoji_large.png"
    # safari_pinned_tab: "Thinking_Face_Emoji_large.png"

  label:
    text: "Home"
    # icon: Thinking_Face_Emoji_large.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome to watobi pages!"
    subtitle: "技術的なことを中心にブログを書いていきます。"
    imageUrl: "watobi.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image
    buttons:
    #   - name: Posts
    #    url: posts
    #   - name: Tags
    #     url: tags

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
  #  - name: twitter
  #    url: "https://twitter.com/"
    - name: github
      url: "https://github.com/watobii"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://watobii.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 7
    - identifier: tags
      name: tags
      url: /tags/
      weight: 14
    - identifier: profile
      name: profile
      url: /profile/
      weight: 21
    - identifier: posts
      name: posts
      url: posts
      weight: 28
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
#pygmentsUseClasses: true
#markup:
#  highlight:
#    noClasses: false
#    anchorLineNos: true
#    codeFences: true
#    guessSyntax: true
#    lineNos: true
#    style: monokai