baseURL: "https://watobii.github.io/"
canonifyurls: false
publishDir: "docs"
title: watobi's page
paginate: 5
theme: PaperMod
languageCode: "ja-jp"

enableEmoji: true
enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: watobi
  description: "Blog of watobi."
  keywords: [Blog, Portfolio, PaperMod]
  author: watobi
  # author: ["Me", "You"] # multiple authors
  images:
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "pen.png"
    favicon16x16: "pen.png"
    favicon32x32: "pen.png"
    apple_touch_icon: "pen.png"
    safari_pinned_tab: "pen.png"

  label:
    text: "Home"
    # icon: Thinking_Face_Emoji_large.png
    iconHeight: 35

  # profile-mode
  #profileMode:
  #  enabled: true # needs to be explicitly set
  #  title: "Welcome to watobi pages!"
  #  subtitle: "技術的なことを中心にブログを書いていきます。"
  #  imageUrl: "watobi.jpg"
  #  imageWidth: 200
  #  imageHeight: 200
  #  imageTitle: my image
    # buttons:
    #   - name: Posts
    #    url: posts
    #   - name: Tags
    #     url: tags

  # home-info mode
  homeInfoParams:
     Title: "This is watobi's page 😁"
     Content: 技術的なことを中心に書いていきます！

  socialIcons:
    - name: email
      url: "https://docs.google.com/forms/d/e/1FAIpQLSdsFw4jCJzzFd8mXAabFBG0aXVgvqWjX0sDfHOTXnUcXpmWlg/viewform?usp=sf_link"
    - name: twitter
      url: "https://twitter.com/watobi_pub"
    - name: github
      url: "https://github.com/watobii"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
  #  URL: "https://watobii.github.io/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
  #  - identifier: categories
  #    name: categories
  #    url: /categories/
  #    weight: 7
    - identifier: Profile
      name: Profile
      url: fixed/profile/
      weight: 10
    - identifier: Posts
      name: Posts
      url: posts
      weight: 20
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
#    anchorLineNos: true
#    codeFences: true
#    guessSyntax: true
#    lineNos: true
#    style: monokai